# This file was generated by GoReleaser. DO NOT EDIT.
cask "notion-seed" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5ad66d5149fab37fcc042420dc77946872fd0125019e7d59677a6de650a59278"
      url "https://github.com/Tykok/notion-seed/releases/download/v#{version}/notion-seed_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "70642fbd8aa8f0803ab844ddef488e06ca93cd30713b6dd300eb34f717c20166"
      url "https://github.com/Tykok/notion-seed/releases/download/v#{version}/notion-seed_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ea2c23e9d5eb9cbe744a31d88df3e1ccf18957fddf2f99fb0e511b28fc76add"
      url "https://github.com/Tykok/notion-seed/releases/download/v#{version}/notion-seed_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "483671b96fec9b51fa1f769a46ed6dbff77b84ecbc313bc6f69069daf7c4ae8a"
      url "https://github.com/Tykok/notion-seed/releases/download/v#{version}/notion-seed_#{version}_linux_amd64.tar.gz"
    end
  end

  name "notion-seed"
  desc "Déclare la structure d'un workspace Notion et refuse les changements destructifs"
  homepage "https://github.com/tykok/notion-seed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notion-seed"

  postflight do
    # Le binaire n'est pas notarié : sans ça macOS le met en quarantaine
    # et refuse de l'exécuter, avec un message qui parle de développeur
    # non vérifié plutôt que de quarantaine.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notion-seed"]
    end
  end

  # No zap stanza required
end
